// <auto-generated />
using System;
using GTAuto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GTAuto.Data.Migrations
{
    [DbContext(typeof(GTAutoDbContext))]
    [Migration("20260416091034_FixedDeterministicImageGuids")]
    partial class FixedDeterministicImageGuids
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GTAuto.Data.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "General"
                        });
                });

            modelBuilder.Entity("GTAuto.Data.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFlashOffer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Color = "Green",
                            Description = "M-Track Package, Carbon Seats, Laser Lights, Like new!",
                            FuelType = "Petrol",
                            HorsePower = 510,
                            IsAutomatic = true,
                            IsFlashOffer = false,
                            IsReserved = false,
                            IsSold = false,
                            Mileage = 8500,
                            ModelId = new Guid("aaaa0000-0000-0000-0000-000000000001"),
                            Price = 145000m,
                            Transmission = "Automatic",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Color = "Grey",
                            Description = "Ceramic Brakes, RS Dynamic Plus, Bang & Olufsen.",
                            FuelType = "Petrol",
                            HorsePower = 600,
                            IsAutomatic = true,
                            IsFlashOffer = false,
                            IsReserved = false,
                            IsSold = false,
                            Mileage = 1200,
                            ModelId = new Guid("aaaa0000-0000-0000-0000-000000000002"),
                            Price = 178000m,
                            Transmission = "Automatic",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Color = "Black",
                            Description = "AMG Night Package, Performance Exhaust.",
                            FuelType = "Petrol",
                            HorsePower = 530,
                            IsAutomatic = true,
                            IsFlashOffer = false,
                            IsReserved = false,
                            IsSold = false,
                            Mileage = 14000,
                            ModelId = new Guid("aaaa0000-0000-0000-0000-000000000003"),
                            Price = 155000m,
                            Transmission = "Automatic",
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            Color = "White",
                            Description = "Stage 1, Akrapovic tips, Edition 35 wheels.",
                            FuelType = "Petrol",
                            HorsePower = 211,
                            IsAutomatic = false,
                            IsFlashOffer = false,
                            IsReserved = false,
                            IsSold = false,
                            Mileage = 155000,
                            ModelId = new Guid("aaaa0000-0000-0000-0000-000000000004"),
                            Price = 18000m,
                            Transmission = "Manual",
                            Year = 2012
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000005"),
                            Color = "Red",
                            Description = "Plaid version, Ludicrous mode, Full self-driving.",
                            FuelType = "Electric",
                            HorsePower = 1020,
                            IsAutomatic = true,
                            IsFlashOffer = false,
                            IsReserved = false,
                            IsSold = false,
                            Mileage = 10000,
                            ModelId = new Guid("aaaa0000-0000-0000-0000-000000000005"),
                            Price = 95000m,
                            Transmission = "Automatic",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000006"),
                            Color = "Blue",
                            Description = "M-Sport, Sky Lounge, Harman Kardon.",
                            FuelType = "Diesel",
                            HorsePower = 400,
                            IsAutomatic = true,
                            IsFlashOffer = false,
                            IsReserved = false,
                            IsSold = false,
                            Mileage = 5000,
                            ModelId = new Guid("aaaa0000-0000-0000-0000-000000000006"),
                            Price = 110000m,
                            Transmission = "Automatic",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000007"),
                            Color = "Silver",
                            Description = "S-line, Matrix lights, Virtual cockpit.",
                            FuelType = "Diesel",
                            HorsePower = 286,
                            IsAutomatic = true,
                            IsFlashOffer = false,
                            IsReserved = false,
                            IsSold = false,
                            Mileage = 65000,
                            ModelId = new Guid("aaaa0000-0000-0000-0000-000000000007"),
                            Price = 55000m,
                            Transmission = "Automatic",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000008"),
                            Color = "Blue",
                            Description = "Brand new, 10 years warranty, Hybrid system.",
                            FuelType = "Hybrid",
                            HorsePower = 140,
                            IsAutomatic = true,
                            IsFlashOffer = false,
                            IsReserved = false,
                            IsSold = false,
                            Mileage = 0,
                            ModelId = new Guid("aaaa0000-0000-0000-0000-000000000008"),
                            Price = 32000m,
                            Transmission = "Automatic",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000009"),
                            Color = "Matte Black",
                            Description = "G63 AMG, Night Package, Carbon interior.",
                            FuelType = "Petrol",
                            HorsePower = 585,
                            IsAutomatic = true,
                            IsFlashOffer = false,
                            IsReserved = false,
                            IsSold = false,
                            Mileage = 12000,
                            ModelId = new Guid("aaaa0000-0000-0000-0000-000000000009"),
                            Price = 235000m,
                            Transmission = "Automatic",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000010"),
                            Color = "Red",
                            Description = "Collector's car, Perfect condition, V8 Manual.",
                            FuelType = "Petrol",
                            HorsePower = 400,
                            IsAutomatic = false,
                            IsFlashOffer = false,
                            IsReserved = false,
                            IsSold = false,
                            Mileage = 180000,
                            ModelId = new Guid("aaaa0000-0000-0000-0000-000000000010"),
                            Price = 45000m,
                            Transmission = "Manual",
                            Year = 2002
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000011"),
                            Color = "White",
                            Description = "AMG Performance, Panoramic roof, Full service history.",
                            FuelType = "Petrol",
                            HorsePower = 525,
                            IsAutomatic = true,
                            IsFlashOffer = false,
                            IsReserved = false,
                            IsSold = false,
                            Mileage = 160000,
                            ModelId = new Guid("aaaa0000-0000-0000-0000-000000000011"),
                            Price = 38000m,
                            Transmission = "Automatic",
                            Year = 2014
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000012"),
                            Color = "Orange",
                            Description = "Fox Shocks, 37 Performance Package, Off-road monster.",
                            FuelType = "Petrol",
                            HorsePower = 450,
                            IsAutomatic = true,
                            IsFlashOffer = false,
                            IsReserved = false,
                            IsSold = false,
                            Mileage = 2000,
                            ModelId = new Guid("aaaa0000-0000-0000-0000-000000000012"),
                            Price = 125000m,
                            Transmission = "Automatic",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000013"),
                            Color = "Yellow",
                            Description = "Lamborghini Urus Performante, Titanium Exhaust.",
                            FuelType = "Petrol",
                            HorsePower = 666,
                            IsAutomatic = true,
                            IsFlashOffer = false,
                            IsReserved = false,
                            IsSold = false,
                            Mileage = 1500,
                            ModelId = new Guid("aaaa0000-0000-0000-0000-000000000013"),
                            Price = 350000m,
                            Transmission = "Automatic",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000014"),
                            Color = "Sunset Orange",
                            Description = "Widebody, Custom wheels, Drift setup.",
                            FuelType = "Petrol",
                            HorsePower = 350,
                            IsAutomatic = false,
                            IsFlashOffer = false,
                            IsReserved = false,
                            IsSold = false,
                            Mileage = 120000,
                            ModelId = new Guid("aaaa0000-0000-0000-0000-000000000014"),
                            Price = 25000m,
                            Transmission = "Manual",
                            Year = 2007
                        });
                });

            modelBuilder.Entity("GTAuto.Data.Models.CarFeature", b =>
                {
                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CarId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("CarFeatures");
                });

            modelBuilder.Entity("GTAuto.Data.Models.CarImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000001"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            ImagePath = "/images/cars/m4-front.jpg",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000002"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            ImagePath = "/images/cars/m4-back.jpg",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000003"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            ImagePath = "/images/cars/m4-interior.jpg",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000004"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            ImagePath = "/images/cars/rs7-front.jpg",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000005"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            ImagePath = "/images/cars/rs7-back.jpg",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000006"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            ImagePath = "/images/cars/rs7-interior.jpg",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000007"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            ImagePath = "/images/cars/gt63-front.jpg",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000008"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            ImagePath = "/images/cars/gt63-back.jpg",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000009"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            ImagePath = "/images/cars/gt63-interior.jpg",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000010"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            ImagePath = "/images/cars/golf6-front.jpg",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000011"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            ImagePath = "/images/cars/golf6-back.jpg",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000012"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            ImagePath = "/images/cars/golf6-interior.jpg",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000013"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            ImagePath = "/images/cars/tesla-front.jpg",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000014"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            ImagePath = "/images/cars/tesla-back.jpg",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000015"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            ImagePath = "/images/cars/tesla-interior.jpg",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000016"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            ImagePath = "/images/cars/x5-front.jpg",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000017"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            ImagePath = "/images/cars/x5-back.jpg",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000018"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            ImagePath = "/images/cars/x5-interior.jpg",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000019"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000007"),
                            ImagePath = "/images/cars/a6-front.jpg",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000020"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000007"),
                            ImagePath = "/images/cars/a6-back.jpg",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000021"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000007"),
                            ImagePath = "/images/cars/a6-interior.jpg",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000022"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000008"),
                            ImagePath = "/images/cars/toyota-front.jpg",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000023"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000008"),
                            ImagePath = "/images/cars/toyota-back.jpg",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000024"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000008"),
                            ImagePath = "/images/cars/toyota-interior.jpg",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000025"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000009"),
                            ImagePath = "/images/cars/gclass-front.jpg",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000026"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000009"),
                            ImagePath = "/images/cars/gclass-back.jpg",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000027"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000009"),
                            ImagePath = "/images/cars/gclass-interior.jpg",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000028"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000010"),
                            ImagePath = "/images/cars/e39-front.jpg",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000029"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000010"),
                            ImagePath = "/images/cars/e39-back.jpg",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000030"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000010"),
                            ImagePath = "/images/cars/e39-interior.jpg",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000031"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000011"),
                            ImagePath = "/images/cars/ml63-front.jpg",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000032"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000011"),
                            ImagePath = "/images/cars/ml63-back.jpg",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000033"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000011"),
                            ImagePath = "/images/cars/ml63-interior.jpg",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000034"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000012"),
                            ImagePath = "/images/cars/f150-front.jpg",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000035"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000012"),
                            ImagePath = "/images/cars/f150-back.jpg",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000036"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000012"),
                            ImagePath = "/images/cars/f150-interior.jpg",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000037"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000013"),
                            ImagePath = "/images/cars/urus-front.jpg",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000038"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000013"),
                            ImagePath = "/images/cars/urus-back.jpg",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000039"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000013"),
                            ImagePath = "/images/cars/urus-interior.jpg",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000040"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000014"),
                            ImagePath = "/images/cars/350z-front.jpg",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000041"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000014"),
                            ImagePath = "/images/cars/350z-back.jpg",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000042"),
                            CarId = new Guid("c0000000-0000-0000-0000-000000000014"),
                            ImagePath = "/images/cars/350z-interior.jpg",
                            Order = 3
                        });
                });

            modelBuilder.Entity("GTAuto.Data.Models.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("GTAuto.Data.Models.Fuel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FuelConsumption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fuels");
                });

            modelBuilder.Entity("GTAuto.Data.Models.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa0000-0000-0000-0000-000000000001"),
                            BrandId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "BMW M4 Competition"
                        },
                        new
                        {
                            Id = new Guid("aaaa0000-0000-0000-0000-000000000002"),
                            BrandId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Audi RS7"
                        },
                        new
                        {
                            Id = new Guid("aaaa0000-0000-0000-0000-000000000003"),
                            BrandId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Mercedes AMG GT"
                        },
                        new
                        {
                            Id = new Guid("aaaa0000-0000-0000-0000-000000000004"),
                            BrandId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "VW Golf 6 GTI"
                        },
                        new
                        {
                            Id = new Guid("aaaa0000-0000-0000-0000-000000000005"),
                            BrandId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Tesla Model S"
                        },
                        new
                        {
                            Id = new Guid("aaaa0000-0000-0000-0000-000000000006"),
                            BrandId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "BMW X5"
                        },
                        new
                        {
                            Id = new Guid("aaaa0000-0000-0000-0000-000000000007"),
                            BrandId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Audi A6"
                        },
                        new
                        {
                            Id = new Guid("aaaa0000-0000-0000-0000-000000000008"),
                            BrandId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Toyota Corolla"
                        },
                        new
                        {
                            Id = new Guid("aaaa0000-0000-0000-0000-000000000009"),
                            BrandId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Mercedes G-Class"
                        },
                        new
                        {
                            Id = new Guid("aaaa0000-0000-0000-0000-000000000010"),
                            BrandId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "BMW М5 Е39"
                        },
                        new
                        {
                            Id = new Guid("aaaa0000-0000-0000-0000-000000000011"),
                            BrandId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Mercedes ML 63 AMG"
                        },
                        new
                        {
                            Id = new Guid("aaaa0000-0000-0000-0000-000000000012"),
                            BrandId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Ford F150 Raptor"
                        },
                        new
                        {
                            Id = new Guid("aaaa0000-0000-0000-0000-000000000013"),
                            BrandId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Lamborghini Urus"
                        },
                        new
                        {
                            Id = new Guid("aaaa0000-0000-0000-0000-000000000014"),
                            BrandId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Nissan 350Z Tuned"
                        });
                });

            modelBuilder.Entity("GTAuto.Data.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GTAuto.Data.Models.OrderStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Approved")
                        .HasColumnType("int");

                    b.Property<int>("Cancelled")
                        .HasColumnType("int");

                    b.Property<int>("Pending")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("GTAuto.Data.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DepositPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("GTAuto.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GTAuto.Data.Models.Car", b =>
                {
                    b.HasOne("GTAuto.Data.Models.Model", "Model")
                        .WithMany("Cars")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("GTAuto.Data.Models.CarFeature", b =>
                {
                    b.HasOne("GTAuto.Data.Models.Car", "Car")
                        .WithMany("CarFeatures")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GTAuto.Data.Models.Feature", "Feature")
                        .WithMany("CarFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("GTAuto.Data.Models.CarImage", b =>
                {
                    b.HasOne("GTAuto.Data.Models.Car", "Car")
                        .WithMany("Images")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("GTAuto.Data.Models.Model", b =>
                {
                    b.HasOne("GTAuto.Data.Models.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("GTAuto.Data.Models.Order", b =>
                {
                    b.HasOne("GTAuto.Data.Models.Car", "Car")
                        .WithMany("Orders")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GTAuto.Data.Models.OrderStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GTAuto.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GTAuto.Data.Models.Reservation", b =>
                {
                    b.HasOne("GTAuto.Data.Models.Car", "Car")
                        .WithMany("Reservations")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GTAuto.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GTAuto.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GTAuto.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GTAuto.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GTAuto.Data.Models.Brand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("GTAuto.Data.Models.Car", b =>
                {
                    b.Navigation("CarFeatures");

                    b.Navigation("Images");

                    b.Navigation("Orders");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("GTAuto.Data.Models.Feature", b =>
                {
                    b.Navigation("CarFeatures");
                });

            modelBuilder.Entity("GTAuto.Data.Models.Model", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
