using GTAuto.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;

namespace GTAuto.Data.Configurations
{
    public class CarsConfiguration : IEntityTypeConfiguration<Car>
    {
        public void Configure(EntityTypeBuilder<Car> builder)
        {
            builder.HasData(
                new Car { Id = Guid.NewGuid(), ModelId = Guid.Parse("11111111-1111-1111-1111-111111111111"), Year = 2022, HorsePower = 670, Price = 185000, Mileage = 12000, FuelType = "Petrol", Transmission = "Automatic", Color = "Dark grey", Description = "Well maintained car, no accidents, full service history.", ImageUrl = "/images/cars/bmw1.jpg", IsReserved = false, IsSold = false, IsAutomatic = false },
                new Car { Id = Guid.NewGuid(), ModelId = Guid.Parse("22222222-2222-2222-2222-222222222222"), Year = 2020, HorsePower = 190, Price = 25000, Mileage = 80000, FuelType = "Petrol", Transmission = "Automatic", Color = "White", Description = "Like new condition, fully loaded, automatic gearbox.", ImageUrl = "/images/cars/audi.jpg", IsReserved = false, IsSold = false, IsAutomatic = true },
                new Car { Id = Guid.NewGuid(), ModelId = Guid.Parse("33333333-3333-3333-3333-333333333333"), Year = 2015, HorsePower = 110, Price = 9500, Mileage = 160000, FuelType = "Diesel", Transmission = "Manual", Color = "Grey", Description = "Reliable and economic car, perfect for daily driving.", ImageUrl = "/images/cars/vw_golf.jpg", IsReserved = false, IsSold = false, IsAutomatic = false },
                new Car { Id = Guid.NewGuid(), ModelId = Guid.Parse("44444444-4444-4444-4444-444444444444"), Year = 2019, HorsePower = 200, Price = 30000, Mileage = 60000, FuelType = "Petrol", Transmission = "Automatic", Color = "Red", Description = "Sporty sedan, excellent performance, low mileage.", ImageUrl = "/images/cars/mercedes1.jpg", IsReserved = false, IsSold = false, IsAutomatic = true },
                new Car { Id = Guid.NewGuid(), ModelId = Guid.Parse("55555555-5555-5555-5555-555555555555"), Year = 2017, HorsePower = 140, Price = 15000, Mileage = 110000, FuelType = "Diesel", Transmission = "Manual", Color = "Blue", Description = "Comfortable family car, regular maintenance done.", ImageUrl = "/images/cars/ford_focus.jpg", IsReserved = false, IsSold = false, IsAutomatic = false },
                new Car { Id = Guid.NewGuid(), ModelId = Guid.Parse("66666666-6666-6666-6666-666666666666"), Year = 2021, HorsePower = 220, Price = 35000, Mileage = 40000, FuelType = "Petrol", Transmission = "Automatic", Color = "Silver", Description = "Luxury SUV, perfect condition, full options.", ImageUrl = "/images/cars/bmw_x5.jpg", IsReserved = false, IsSold = false, IsAutomatic = true },
                new Car { Id = Guid.NewGuid(), ModelId = Guid.Parse("77777777-7777-7777-7777-777777777777"), Year = 2016, HorsePower = 130, Price = 12000, Mileage = 140000, FuelType = "Diesel", Transmission = "Manual", Color = "White", Description = "Economical hatchback, ideal for city driving.", ImageUrl = "/images/cars/renault_clio.jpg", IsReserved = false, IsSold = false, IsAutomatic = false },
                new Car { Id = Guid.NewGuid(), ModelId = Guid.Parse("88888888-8888-8888-8888-888888888888"), Year = 2019, HorsePower = 180, Price = 22000, Mileage = 90000, FuelType = "Petrol", Transmission = "Automatic", Color = "Black", Description = "Reliable SUV, spacious interior, perfect for family.", ImageUrl = "/images/cars/toyota_rav4.jpg", IsReserved = false, IsSold = false, IsAutomatic = true },
                new Car { Id = Guid.NewGuid(), ModelId = Guid.Parse("99999999-9999-9999-9999-999999999999"), Year = 2014, HorsePower = 100, Price = 8500, Mileage = 170000, FuelType = "Diesel", Transmission = "Manual", Color = "Grey", Description = "Small city car, low running costs, reliable.", ImageUrl = "/images/cars/fiat_punto.jpg", IsReserved = false, IsSold = false, IsAutomatic = false },
                new Car { Id = Guid.NewGuid(), ModelId = Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"), Year = 2020, HorsePower = 210, Price = 28000, Mileage = 70000, FuelType = "Petrol", Transmission = "Automatic", Color = "Blue", Description = "Compact SUV, modern design, well maintained.", ImageUrl = "/images/cars/hyundai_tucson.jpg", IsReserved = false, IsSold = false, IsAutomatic = true },
                new Car { Id = Guid.NewGuid(), ModelId = Guid.Parse("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"), Year = 2017, HorsePower = 160, Price = 16000, Mileage = 100000, FuelType = "Diesel", Transmission = "Manual", Color = "White", Description = "Reliable sedan, suitable for daily commute.", ImageUrl = "/images/cars/opel_astra.jpg", IsReserved = false, IsSold = false, IsAutomatic = false },
                new Car { Id = Guid.NewGuid(), ModelId = Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccccc"), Year = 2018, HorsePower = 170, Price = 20000, Mileage = 95000, FuelType = "Petrol", Transmission = "Automatic", Color = "Red", Description = "Sporty hatchback, well maintained, low mileage.", ImageUrl = "/images/cars/seat_leon.jpg", IsReserved = false, IsSold = false, IsAutomatic = true },
                new Car { Id = Guid.NewGuid(), ModelId = Guid.Parse("dddddddd-dddd-dddd-dddd-dddddddddddd"), Year = 2015, HorsePower = 120, Price = 11000, Mileage = 130000, FuelType = "Diesel", Transmission = "Manual", Color = "Silver", Description = "Compact family car, reliable and efficient.", ImageUrl = "/images/cars/skoda_fabia.jpg", IsReserved = false, IsSold = false, IsAutomatic = false },
                new Car { Id = Guid.NewGuid(), ModelId = Guid.Parse("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"), Year = 2021, HorsePower = 230, Price = 40000, Mileage = 30000, FuelType = "Petrol", Transmission = "Automatic", Color = "Black", Description = "High-end SUV, almost new, fully equipped.", ImageUrl = "/images/cars/volvo_xc90.jpg", IsReserved = false, IsSold = false, IsAutomatic = true },
                new Car { Id = Guid.NewGuid(), ModelId = Guid.Parse("ffffffff-ffff-ffff-ffff-ffffffffffff"), Year = 2016, HorsePower = 550, Price = 150000, Mileage = 20000, FuelType = "Petrol", Transmission = "Automatic", Color = "Yellow", Description = "Tuned Lamborghini Urus, high performance, like new.", ImageUrl = "/images/cars/lamborghini_urus.jpg", IsReserved = false, IsSold = false, IsAutomatic = true }
            );
        }
    }
}